name: PlayTimeLimiter
version: 1.0-SNAPSHOT
main: rdhuht.github.playtimelimiter.PlayTimeLimiter
authors: [Rdhuht]
description: 我的世界游戏时间限制插件
depend: [ActionBarAPI]
commands:
  playtime:
    description: Commands for the PlayTimeLimiter plugin relating to players time played.
    aliases: pt
permissions:
  playtimelimiter.*:
    description: Gives access to all PlayTimeLimiter commands.
    children:
      playtimelimiter.playtime.add: true
      playtimelimiter.playtime.remove: true
      playtimelimiter.playtime.set: true
      playtimelimiter.playtime.check.self: true
      playtimelimiter.playtime.check.others: true
      playtimelimiter.playtime.start: true
      playtimelimiter.playtime.stop: true
  playtimelimiter.playtime.add:
    description: Gives access to be able to add time to a players play time.
    default: op
  playtimelimiter.playtime.remove:
    description: Gives access to be able to remove time from a players play time.
    default: op
  playtimelimiter.playtime.set:
    description: Set a player's playtime in seconds.
    default: op
  playtimelimiter.playtime.check.self:
    description: Gives access to the /playtime check command to check own playtime.
    default: true
  playtimelimiter.playtime.check.others:
    description: Gives access to the /playtime check command to check others playtime.
    default: op
  playtimelimiter.playtime.start:
    description: Gives access to the /playtime start command which starts the timer.
    default: op
  playtimelimiter.playtime.stop:
    description: Gives access to the /playtime stop command which stops the timer.
    default: op